### ISSUE TITLE
typeguard needs newer typing-extensions

### ISSUE THREAD

**Issue by mattgodbolt** [conda-forge/typeguard-feedstock#28]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Using typeguard can end up with errors like:

"/home/mgodbolt/dev/tradewinds/out/env/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/home/mgodbolt/dev/tradewinds/out/env/lib/python3.10/site-packages/typeguard/_importhook.py", line 22, in <module>
    from typing_extensions import Buffer
ImportError: cannot import name 'Buffer' from 'typing_extensions' 

as typeguard needs a newer version of typing_extensions -- in the upstream pacakge https://github.com/agronholm/typeguard/blob/master/pyproject.toml

which says:
```
dependencies = [
    "importlib_metadata >= 3.6; python_version < '3.10'",
    "typing_extensions >= 4.7.0; python_version < '3.12'",
]
```

### Installed packages

```shell
$ conda list -p out/env
# packages in environment at /home/mgodbolt/dev/tradewinds/out/env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://conda.aq.tc/base
_openmp_mutex             4.5                  2_kmp_llvm    https://conda.aq.tc/base
aiobotocore               2.5.0              pyhd8ed1ab_0    https://conda.aq.tc/base
aiocron                   1.8                pyhd8ed1ab_0    https://conda.aq.tc/base
aiohttp                   3.8.5           py310h2372a71_0    https://conda.aq.tc/base
aioitertools              0.11.0             pyhd8ed1ab_0    https://conda.aq.tc/base
aiokafka                  0.7.2           py310h5764c6d_2    https://conda.aq.tc/base
aiosignal                 1.3.1              pyhd8ed1ab_0    https://conda.aq.tc/base
aq-base-python-310        37.187                        0    https://conda.aq.tc/base
aq-bloomberg              19              py310h57dc785_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-chantey                227             py310h0fefb24_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-datacube               258             py310h02d25a9_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-dfvalidators           48                       pypy_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-envysync               23              py310h3a55366_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-fincal                 63              py310hc997784_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-hotsocket              33                         py_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-lake-client            162             py310h57dc785_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-libdatacube            0.142                h35c58de_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-libwave                1.680                h35c58de_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-lifevest               45              py310h57dc785_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-meter                  213             py310h57dc785_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-porthole               2372            py310h0fefb24_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-promstatsd             14              py310h57dc785_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-pywave                 1.680                hb578a28_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-reservoir              245             py310hf2939db_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-wave                   1.680                h35c58de_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
aq-yard                   7226                    py310_0    https://artifactory.aq.tc/artifactory/api/conda/core-conda-rel
arrow-cpp                 11.0.0           ha770c72_9_cpu    https://conda.aq.tc/base
astroid                   2.15.6          py310hff52083_0    https://conda.aq.tc/base
async-timeout             4.0.2              pyhd8ed1ab_0    https://conda.aq.tc/base
asyncssh                  2.13.2             pyhd8ed1ab_0    https://conda.aq.tc/base
attrs                     23.1.0             pyh71513ae_1    https://conda.aq.tc/base
aws-c-auth                0.6.26               h987a71b_2    https://conda.aq.tc/base
aws-c-cal                 0.5.21               h48707d8_2    https://conda.aq.tc/base
aws-c-common              0.8.14               h0b41bf4_0    https://conda.aq.tc/base
aws-c-compression         0.2.16               h03acc5a_5    https://conda.aq.tc/base
aws-c-event-stream        0.2.20               h00877a2_4    https://conda.aq.tc/base
aws-c-http                0.7.6                hf342b9f_0    https://conda.aq.tc/base
aws-c-io                  0.13.19              h5b20300_3    https://conda.aq.tc/base
aws-c-mqtt                0.8.6               hc4349f7_12    https://conda.aq.tc/base
aws-c-s3                  0.2.7                h909e904_1    https://conda.aq.tc/base
aws-c-sdkutils            0.1.9                h03acc5a_0    https://conda.aq.tc/base
aws-checksums             0.1.14               h03acc5a_5    https://conda.aq.tc/base
aws-crt-cpp               0.19.8              hf7fbfca_12    https://conda.aq.tc/base
aws-sdk-cpp               1.10.57              h17c43bd_8    https://conda.aq.tc/base
bellport                  1.0.15755            h76dd9c9_0    https://conda.aq.tc/base
benchmark                 1.8.2                h59595ed_0    https://conda.aq.tc/base
binutils_impl_linux-64    2.39                 he00db2b_1    https://conda.aq.tc/base
binutils_linux-64         2.39                h5fc0e48_13    https://conda.aq.tc/base
blosc                     1.21.4               h0f2a231_0    https://conda.aq.tc/base
blosc-hdf5-plugin         1.0.0                h91a81c6_5    https://conda.aq.tc/base
boost-cpp                 1.78.0               h5adbc97_2    https://conda.aq.tc/base
boto3                     1.26.76            pyhd8ed1ab_0    https://conda.aq.tc/base
botocore                  1.29.76            pyhd8ed1ab_0    https://conda.aq.tc/base
brotlipy                  0.7.0           py310h5764c6d_1005    https://conda.aq.tc/base
bzip2                     1.0.8                h7f98852_4    https://conda.aq.tc/base
c-ares                    1.19.1               hd590300_0    https://conda.aq.tc/base
c-blosc2                  2.8.0                hf91038e_1    https://conda.aq.tc/base
ca-certificates           2023.7.22            hbcca054_0    https://conda.aq.tc/base
cached-property           1.5.2                hd8ed1ab_1    https://conda.aq.tc/base
cached_property           1.5.2              pyha770c72_1    https://conda.aq.tc/base
catch2                    3.4.0                h00ab1b0_0    https://conda.aq.tc/base
certifi                   2023.7.22          pyhd8ed1ab_0    https://conda.aq.tc/base
cffi                      1.15.1          py310h255011f_3    https://conda.aq.tc/base
charset-normalizer        3.2.0              pyhd8ed1ab_0    https://conda.aq.tc/base
clang                     15.0.7               ha770c72_2    https://conda.aq.tc/base
clang-15                  15.0.7          default_h7634d5b_2    https://conda.aq.tc/base
clang-format              15.0.7          default_h7634d5b_2    https://conda.aq.tc/base
clang-format-15           15.0.7          default_h7634d5b_2    https://conda.aq.tc/base
clang-tools               15.0.7          default_h7634d5b_2    https://conda.aq.tc/base
clangxx                   15.0.7          default_h1e1816b_2    https://conda.aq.tc/base
click                     8.1.3           unix_pyhd8ed1ab_2    https://conda.aq.tc/base
cloudpickle               2.2.1              pyhd8ed1ab_0    https://conda.aq.tc/base
cmake                     3.26.4               hcfe8598_0    https://conda.aq.tc/base
colorama                  0.4.6              pyhd8ed1ab_0    https://conda.aq.tc/base
croniter                  0.3.36             pyhd8ed1ab_0    https://conda.aq.tc/base
cryptography              41.0.2          py310h75e40e8_0    https://conda.aq.tc/base
cyrus-sasl                2.1.27               h9033bb2_6    https://conda.aq.tc/base
decorator                 5.1.1              pyhd8ed1ab_0    https://conda.aq.tc/base
dill                      0.3.6              pyhd8ed1ab_1    https://conda.aq.tc/base
exceptiongroup            1.1.2              pyhd8ed1ab_0    https://conda.aq.tc/base
execnet                   2.0.2              pyhd8ed1ab_0    https://conda.aq.tc/base
expat                     2.5.0                hcb278e6_1    https://conda.aq.tc/base
fast_float                5.2.0                h00ab1b0_0    https://conda.aq.tc/base
filelock                  3.12.2             pyhd8ed1ab_0    https://conda.aq.tc/base
fmt                       9.1.0                h924138e_0    https://conda.aq.tc/base
frozenlist                1.4.0           py310h2372a71_0    https://conda.aq.tc/base
fsspec                    2023.6.0           pyh1a96a4e_0    https://conda.aq.tc/base
gcc_impl_linux-64         12.2.0              hcc96c02_19    https://conda.aq.tc/base
gcc_linux-64              12.2.0              h4798a0e_13    https://conda.aq.tc/base
gflags                    2.2.2             he1b5a44_1004    https://conda.aq.tc/base
glog                      0.6.0                h6f12383_0    https://conda.aq.tc/base
greenlet                  2.0.2           py310hc6cd4ac_1    https://conda.aq.tc/base
grpcio                    1.46.0          py310hba10ccf_1    https://conda.aq.tc/base
gunicorn                  21.2.0          py310hff52083_0    https://conda.aq.tc/base
gxx_impl_linux-64         12.2.0              hcc96c02_19    https://conda.aq.tc/base
gxx_linux-64              12.2.0              hb41e900_13    https://conda.aq.tc/base
h5py                      3.9.0           nompi_py310h367e799_100    https://conda.aq.tc/base
hdf5                      1.14.0          nompi_hb72d44e_103    https://conda.aq.tc/base
hdf5plugin                4.1.3           py310hedae64e_0    https://conda.aq.tc/base
howardhinnant_date        3.0.1                hf99c05c_0    https://conda.aq.tc/base
humanfriendly             10.0            py310hff52083_4    https://conda.aq.tc/base
hvac                      0.11.2             pyhd8ed1ab_0    https://conda.aq.tc/base
icu                       70.1                 h27087fc_0    https://conda.aq.tc/base
idna                      3.4                pyhd8ed1ab_0    https://conda.aq.tc/base
importlib-metadata        6.8.0              pyha770c72_0    https://conda.aq.tc/base
importlib_metadata        6.8.0                hd8ed1ab_0    https://conda.aq.tc/base
iniconfig                 2.0.0              pyhd8ed1ab_0    https://conda.aq.tc/base
intervaltree              3.1.0              pyhd8ed1ab_1    https://conda.aq.tc/base
isort                     5.12.0             pyhd8ed1ab_1    https://conda.aq.tc/base
jinja2                    3.1.2              pyhd8ed1ab_1    https://conda.aq.tc/base
jmespath                  1.0.1              pyhd8ed1ab_0    https://conda.aq.tc/base
json                      3.9.1                         3    https://conda.aq.tc/base
kafka-python              2.0.2.aq.1         pyh1a96a4e_1    https://conda.aq.tc/base
kernel-headers_linux-64   5.4.0                hd8ed1ab_0    https://conda.aq.tc/base
keyutils                  1.6.1                h166bdaf_0    https://conda.aq.tc/base
krb5                      1.20.1               h81ceb04_0    https://conda.aq.tc/base
lazy-object-proxy         1.9.0           py310h1fa729e_0    https://conda.aq.tc/base
ld_impl_linux-64          2.39                 hcc3a1bd_1    https://conda.aq.tc/base
libabseil                 20230125.0      cxx17_hcb278e6_1    https://conda.aq.tc/base
libaec                    1.0.6                hcb278e6_1    https://conda.aq.tc/base
libaio                    0.3.113              h166bdaf_0    https://conda.aq.tc/base
libarrow                  11.0.0           h33598ff_9_cpu    https://conda.aq.tc/base
libblas                   3.9.0            16_linux64_mkl    https://conda.aq.tc/base
libbrotlicommon           1.0.9                h166bdaf_9    https://conda.aq.tc/base
libbrotlidec              1.0.9                h166bdaf_9    https://conda.aq.tc/base
libbrotlienc              1.0.9                h166bdaf_9    https://conda.aq.tc/base
libcblas                  3.9.0            16_linux64_mkl    https://conda.aq.tc/base
libclang                  15.0.7          default_h7634d5b_2    https://conda.aq.tc/base
libclang-cpp15            15.0.7          default_h7634d5b_2    https://conda.aq.tc/base
libclang13                15.0.7          default_h9986a30_2    https://conda.aq.tc/base
libcrc32c                 1.1.2                h9c3ff4c_0    https://conda.aq.tc/base
libcurl                   8.1.2                h409715c_0    https://conda.aq.tc/base
libedit                   3.1.20191231         he28a2e2_2    https://conda.aq.tc/base
libev                     4.33                 h516909a_1    https://conda.aq.tc/base
libevent                  2.1.10               h28343ad_4    https://conda.aq.tc/base
libexpat                  2.5.0                hcb278e6_1    https://conda.aq.tc/base
libffi                    3.4.2                h7f98852_5    https://conda.aq.tc/base
libgcc-devel_linux-64     12.2.0              h3b97bd3_19    https://conda.aq.tc/base
libgcc-ng                 12.2.0              h65d4601_19    https://conda.aq.tc/base
libgfortran-ng            12.2.0              h69a702a_19    https://conda.aq.tc/base
libgfortran5              12.2.0              h337968e_19    https://conda.aq.tc/base
libgomp                   12.2.0              h65d4601_19    https://conda.aq.tc/base
libgoogle-cloud           2.8.0                h3c06191_0    https://conda.aq.tc/base
libgrpc                   1.51.1               hcf146ea_3    https://conda.aq.tc/base
libhwloc                  2.9.1                hd6dc26d_0    https://conda.aq.tc/base
libiconv                  1.17                 h166bdaf_0    https://conda.aq.tc/base
liblapack                 3.9.0            16_linux64_mkl    https://conda.aq.tc/base
libllvm15                 15.0.7               hadd5161_1    https://conda.aq.tc/base
libnghttp2                1.52.0               h61bc06f_0    https://conda.aq.tc/base
libnsl                    2.0.0                h7f98852_0    https://conda.aq.tc/base
libntlm                   1.4               h7f98852_1002    https://conda.aq.tc/base
libpcap                   1.10.4               hd590300_1    https://conda.aq.tc/base
libpq                     15.2                 hb675445_0    https://conda.aq.tc/base
libprotobuf               3.21.12              h3eb15da_0    https://conda.aq.tc/base
librdkafka                2.1.1                hfe68a65_0    https://conda.aq.tc/base
libsanitizer              12.2.0              h46fd767_19    https://conda.aq.tc/base
libsqlite                 3.42.0               h2797004_0    https://conda.aq.tc/base
libssh2                   1.11.0               h0841786_0    https://conda.aq.tc/base
libstdcxx-devel_linux-64  12.2.0              h3b97bd3_19    https://conda.aq.tc/base
libstdcxx-ng              12.2.0              h46fd767_19    https://conda.aq.tc/base
libthrift                 0.18.0               h5e4af38_0    https://conda.aq.tc/base
libutf8proc               2.8.0                h166bdaf_0    https://conda.aq.tc/base
libuuid                   2.38.1               h0b41bf4_0    https://conda.aq.tc/base
libuv                     1.44.2               hd590300_1    https://conda.aq.tc/base
libxml2                   2.10.3               hca2bb57_4    https://conda.aq.tc/base
libzlib                   1.2.13               hd590300_5    https://conda.aq.tc/base
llvm-openmp               15.0.7               h0cdce71_0    https://conda.aq.tc/base
lyra                      1.5.1                         0    https://conda.aq.tc/base
lz4-c                     1.9.4                hcb278e6_0    https://conda.aq.tc/base
lzo                       2.10              h516909a_1000    https://conda.aq.tc/base
markupsafe                2.1.3           py310h2372a71_0    https://conda.aq.tc/base
mccabe                    0.7.0              pyhd8ed1ab_0    https://conda.aq.tc/base
mimalloc                  2.1.1                hcb278e6_0    https://conda.aq.tc/base
mkl                       2022.1.0           h84fe81f_915    https://conda.aq.tc/base
mold                      2.0.0                h913df21_0    https://conda.aq.tc/base
more-itertools            10.0.0             pyhd8ed1ab_0    https://conda.aq.tc/base
ms-gsl                    4.0.0                h00ab1b0_0    https://conda.aq.tc/base
multidict                 6.0.4           py310h1fa729e_0    https://conda.aq.tc/base
multimethod               1.9.1              pyhd8ed1ab_0    https://conda.aq.tc/base
mypy                      1.4.1           py310h2372a71_0    https://conda.aq.tc/base
mypy_extensions           1.0.0              pyha770c72_0    https://conda.aq.tc/base
natsort                   8.4.0              pyhd8ed1ab_0    https://conda.aq.tc/base
ncurses                   6.4                  hcb278e6_0    https://conda.aq.tc/base
ninja                     1.11.1               h924138e_0    https://conda.aq.tc/base
nodejs                    18.15.0              h8d033a5_0    https://conda.aq.tc/base
nptyping                  2.5.0              pyhd8ed1ab_0    https://conda.aq.tc/base
numexpr                   2.8.3           mkl_py310h0afd4a5_1    https://conda.aq.tc/base
numpy                     1.22.4          py310h4ef5377_0    https://conda.aq.tc/base
openssl                   3.1.1                hd590300_1    https://conda.aq.tc/base
orc                       1.8.2                hfdbbad2_2    https://conda.aq.tc/base
packaging                 23.1               pyhd8ed1ab_0    https://conda.aq.tc/base
pandas                    1.5.3           py310h9b08913_1    https://conda.aq.tc/base
pandera                   0.16.1               hd8ed1ab_0    https://conda.aq.tc/base
pandera-base              0.16.1             pyhd8ed1ab_0    https://conda.aq.tc/base
parquet-cpp               1.5.1                         2    https://conda.aq.tc/base
patchelf                  0.17.2               h58526e2_0    https://conda.aq.tc/base
pip                       23.2.1             pyhd8ed1ab_0    https://conda.aq.tc/base
platformdirs              3.5.1              pyhd8ed1ab_0    https://conda.aq.tc/base
pluggy                    1.2.0              pyhd8ed1ab_0    https://conda.aq.tc/base
prometheus-cpp            1.1.0                h751d214_1    https://conda.aq.tc/base
prometheus_client         0.17.1             pyhd8ed1ab_0    https://conda.aq.tc/base
protobuf                  4.21.12         py310heca2aa9_0    https://conda.aq.tc/base
psutil                    5.9.5           py310h1fa729e_0    https://conda.aq.tc/base
psycopg2                  2.9.3           py310h416cc33_2    https://conda.aq.tc/base
py-cpuinfo                9.0.0              pyhd8ed1ab_0    https://conda.aq.tc/base
pyarrow                   11.0.0          py310h633f555_9_cpu    https://conda.aq.tc/base
pycparser                 2.21               pyhd8ed1ab_0    https://conda.aq.tc/base
pydantic                  1.10.12         py310h2372a71_1    https://conda.aq.tc/base
pylint                    2.17.5             pyhd8ed1ab_0    https://conda.aq.tc/base
pyopenssl                 23.2.0             pyhd8ed1ab_1    https://conda.aq.tc/base
pysocks                   1.7.1              pyha2e5f31_6    https://conda.aq.tc/base
pytables                  3.8.0           py310hde6a235_1    https://conda.aq.tc/base
pytest                    7.4.0              pyhd8ed1ab_0    https://conda.aq.tc/base
pytest-aiohttp            0.3.0                      py_0    https://conda.aq.tc/base
pytest-xdist              3.3.1              pyhd8ed1ab_0    https://conda.aq.tc/base
python                    3.10.2          hc74c709_4_cpython    https://conda.aq.tc/base
python-confluent-kafka    2.1.1           py310h2372a71_0    https://conda.aq.tc/base
python-dateutil           2.8.2              pyhd8ed1ab_0    https://conda.aq.tc/base
python-gssapi             1.8.2           py310hd1ceca7_2    https://conda.aq.tc/base
python-rapidjson          1.10            py310heca2aa9_0    https://conda.aq.tc/base
python_abi                3.10                    3_cp310    https://conda.aq.tc/base
pytz                      2023.3             pyhd8ed1ab_0    https://conda.aq.tc/base
pyyaml                    6.0             py310h5764c6d_5    https://conda.aq.tc/base
range-v3                  0.12.0               h59595ed_0    https://conda.aq.tc/base
re2                       2023.02.02           hcb278e6_0    https://conda.aq.tc/base
readline                  8.2                  h8228510_1    https://conda.aq.tc/base
refinitiv-rtsdk           2.0.8.L1.0           h651c8d2_2    https://conda.aq.tc/base
requests                  2.31.0             pyhd8ed1ab_0    https://conda.aq.tc/base
requests-mock             1.11.0             pyhd8ed1ab_0    https://conda.aq.tc/base
retrying                  1.3.3                      py_2    https://conda.aq.tc/base
rfc5424-logging-handler   1.4.3                      py_0    https://conda.aq.tc/base
rhash                     1.4.3                hd590300_1    https://conda.aq.tc/base
s2n                       1.3.41               h3358134_0    https://conda.aq.tc/base
s3fs                      2023.6.0           pyhd8ed1ab_0    https://conda.aq.tc/base
s3transfer                0.6.1              pyhd8ed1ab_0    https://conda.aq.tc/base
seasocks                  1.4.5                h0cdce71_0    https://conda.aq.tc/base
sentry-native             0.6.0                hdd1305a_2    https://conda.aq.tc/base
sentry-sdk                1.28.1             pyhd8ed1ab_0    https://conda.aq.tc/base
setuptools                58.5.3          py310hff52083_0    https://conda.aq.tc/base
six                       1.16.0             pyh6c4a22f_0    https://conda.aq.tc/base
snappy                    1.1.10               h9fff704_0    https://conda.aq.tc/base
solar-capture             1.6.9.1             ha770c72_10    https://conda.aq.tc/base
sortedcontainers          2.4.0              pyhd8ed1ab_0    https://conda.aq.tc/base
spdlog                    1.12.0               h5743cc6_0    https://conda.aq.tc/base
sqlalchemy                1.4.49          py310h2372a71_0    https://conda.aq.tc/base
sqlalchemy-cockroachdb    1.4.4              pyhd8ed1ab_0    https://conda.aq.tc/base
sqlite                    3.42.0               h2c6b66d_0    https://conda.aq.tc/base
statsd                    4.0.1              pyh1a96a4e_0    https://conda.aq.tc/base
sysroot_linux-64          2.31                 hd8ed1ab_0    https://conda.aq.tc/base
tbb                       2021.9.0             hf52228f_0    https://conda.aq.tc/base
tbb-devel                 2021.9.0             hf52228f_0    https://conda.aq.tc/base
tk                        8.6.12               h27826a3_0    https://conda.aq.tc/base
tomli                     2.0.1              pyhd8ed1ab_0    https://conda.aq.tc/base
tomlkit                   0.12.1             pyha770c72_0    https://conda.aq.tc/base
tqdm                      4.65.0             pyhd8ed1ab_1    https://conda.aq.tc/base
trompeloeil               45                   h00ab1b0_0    https://conda.aq.tc/base
typeguard                 4.0.1              pyhd8ed1ab_0    https://conda.aq.tc/base
types-pytz                2023.3.0.0         pyhd8ed1ab_0    https://conda.aq.tc/base
types-requests            2.31.0.2           pyhd8ed1ab_0    https://conda.aq.tc/base
types-urllib3             1.26.25.14         pyhd8ed1ab_0    https://conda.aq.tc/base
typing-extensions         4.5.0                hd8ed1ab_0    https://conda.aq.tc/base
typing_extensions         4.5.0              pyha770c72_0    https://conda.aq.tc/base
typing_inspect            0.9.0              pyhd8ed1ab_0    https://conda.aq.tc/base
typish                    1.9.3              pyhd8ed1ab_0    https://conda.aq.tc/base
tzdata                    2023c                h71feb2d_0    https://conda.aq.tc/base
tzlocal                   5.0.1           py310hff52083_0    https://conda.aq.tc/base
urllib3                   1.26.15            pyhd8ed1ab_0    https://conda.aq.tc/base
wheel                     0.41.0             pyhd8ed1ab_0    https://conda.aq.tc/base
wrapt                     1.15.0          py310h1fa729e_0    https://conda.aq.tc/base
xz                        5.2.6                h166bdaf_0    https://conda.aq.tc/base
yaml                      0.2.5                h7f98852_2    https://conda.aq.tc/base
yarl                      1.9.2           py310h2372a71_0    https://conda.aq.tc/base
zipp                      3.16.2             pyhd8ed1ab_0    https://conda.aq.tc/base
zlib                      1.2.13               hd590300_5    https://conda.aq.tc/base
zlib-ng                   2.0.7                h0b41bf4_0    https://conda.aq.tc/base
zstd                      1.5.2                hfc55251_7    https://conda.aq.tc/base
```

### Environment info

```shell
$ conda info

     active environment : None
       user config file : /home/mgodbolt/.condarc
 populated config files : 
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.6=0
                          __glibc=2.35=0
                          __linux=5.19.0=0
                          __unix=0=0
       base environment : /home/mgodbolt/.cache/ozy/internal_install/conda/4.12.0  (writable)
      conda av data dir : /home/mgodbolt/.cache/ozy/internal_install/conda/4.12.0/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mgodbolt/.cache/ozy/internal_install/conda/4.12.0/pkgs
                          /home/mgodbolt/.conda/pkgs
       envs directories : /home/mgodbolt/.cache/ozy/internal_install/conda/4.12.0/envs
                          /home/mgodbolt/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.10.10 Linux/5.19.0-46-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 5011:5011
             netrc file : None
           offline mode : False
```

**Comment by njzjz** [comment]
I fixed it in #41.

**Comment by jan-janssen** [comment]
To prevent this kind of issues in future, I guess it makes sense to use `grayskull-update` for this package. This is implemented in https://github.com/conda-forge/typeguard-feedstock/pull/42

**Comment by carterbox** [comment]
This is still an issue with a newer typeguard https://github.com/conda-forge/globus-compute-endpoint-feedstock/pull/25

**Comment by njzjz** [comment]
I think #42 is good. Is there any reason to close it?
